services:
  database:
    image: postgres:alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: disysuser
      POSTGRES_PASSWORD: disyspw
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data: